<html><head><meta charset="utf-8"></meta></head><body><h1 class="article-title" style="text-align:center;">PHP7错误处理</h1><div style="width:100%;float:left;" class="article-content">   
 <p style="text-align:justify;"> 从PHP7，错误处理和报告已经改变。PHP5中使用了传统的错误报告机制的错误，现在大多数的错误将通过抛出异常错误处理。类似于异常，这些错误异常会冒泡，直到它们到达第一个匹配的catch块。如果没有匹配的块，那么会使用&nbsp;set_exception_handler()&nbsp;安装一个默认的异常处理并被调用，并在情况下，如果没有默认的异常处理程序，那么该异常将被转换为一个致命的错误，并会像传统错误那样处理。 </p> 
 <p style="text-align:justify;"> 由于&nbsp;Error&nbsp;层次结构不是从异常(Exception)，代码扩展使用catch&nbsp;(Exception $e) { ... }&nbsp;块来处理未捕获的异常，PHP5中将不会处理这样的错误。&nbsp; catch (Error $e) { ... }&nbsp;块或 set_exception_handler()处理程序需要处理的致命错误。 </p> 
 <img src="file://E:/data/youdao/qq24B39E2329F08D9F4C3146A571A415EF/32d1faff60f1406d867a466eb849f45a/on_hiearchy.jpeg" alt="Exception Hiearchy"> 
 <h2> 示例 </h2>   
 <pre>&lt;?php
class MathOperations 
{
   protected $n = 10;

   // Try to get the Division by Zero error object and display as Exception
   public function doOperation(): string
   {
      try {
         $value = $this-&gt;n % 0;
         return $value;
      } catch (DivisionByZeroError $e) {
         return $e-&gt;getMessage();
      }
   }
}

$mathOperationsObj = new MathOperations();
print($mathOperationsObj-&gt;doOperation());
?&gt;</pre> 
 <div>
   浏览器中将产生以下输出- 
 </div> 
 <pre>Modulo by zero</pre>
 <br>      
</div></body></html>