<html><head><meta charset="utf-8"></meta></head><body><h1 class="article-title" style="text-align:center;">Java异常类</h1><div style="width:100%;float:left;" class="article-content">   
 <h2 id="h2-u5F02u5E38u7C7Bu5C42u6B21u7ED3u6784"><a name="异常类层次结构" class="reference-link"></a><span class="header-link octicon octicon-link"></span>异常类层次结构</h2>
 <p>异常类层次结构从<code>java.lang.Throwable</code>类开始。当抛出异常时，它必须是<code>Throwable</code>类的对象或其任何子类。</p> 
 <p><code>catch</code>块的参数必须是<code>Throwable</code>类型或其子类，例如：<code>Exception</code>，<code>ArithmeticException</code>，<code>IOException</code>等。</p> 
 <p>可以通过继承一个异常类类来创建自己定义的异常类。</p> 
 <h2 id="h2--catch-"><a name="组织排列多个catch块" class="reference-link"></a><span class="header-link octicon octicon-link"></span>组织排列多个catch块</h2>
 <p>Java运行时选择适当的<code>catch</code>块，并从第一个<code>catch</code>块开始顺序寻找合适的<code>catch</code>块。<br><code>try</code>块的多个<code>catch</code>块必须从最具体的异常类型排列为最通用的异常类型。</p> 
 <p>以下代码使用多个<code>catch</code>块的有效序列。</p> 
 <p><code>ArithmeticException</code>类是<code>RuntimeException</code>类的子类。</p> 
 <p>如果这两个异常都在同一个<code>try</code>块的<code>catch</code>块中处理，那么最具体的类型，即 <code>ArithmeticException</code>，必须出现在最通用的类型之前，即放在<code>RuntimeException</code>异常类之前。</p> 
 <pre><code class="lang-java">try  {
// Do  something, which  might  throw  Exception
}
catch(ArithmeticException e1)  {
// Handle  ArithmeticException first
}
catch(RuntimeException e2)  {
// Handle  RuntimeException after  ArithmeticException
}
</code></pre> 
 <h2 id="h2-u5DF2u68C0u67E5u548Cu672Au68C0u67E5u5F02u5E38"><a name="已检查和未检查异常" class="reference-link"></a><span class="header-link octicon octicon-link"></span>已检查和未检查异常</h2>
 <p>有三种类型的异常：</p> 
 <ul> 
  <li><p>有一些异常，有更高的发生可能。可以在<code>try-catch</code>块中处理它们。或者在调用方法/构造函数声明中指定抛出异常。</p> </li>
  <li><p>错误是可能发生的异常，并且几乎不能处理它。 例如，<code>java.lang.OutOfMemeoryError</code>。 在程序中也不能做任何事情从内存不足错误中恢复。异常类是层次结构中的类，它们是<code>Error</code>类的子类和<code>Error</code>类，属于此类别的异常。<br>编译器不对这类代码采取处理。如果在运行时抛出此类异常，运行时将通过显示详细的错误消息并暂停应用程序来处理它。</p> </li>
  <li><p>在运行时可能会发生异常，可从异常条件中恢复。<br>异常类是层次结构中的类，它们是<code>RuntimeException</code>类的子类和<code>RuntimeException</code>类本身，属于此类别。</p> </li>
 </ul> 
 <p>第一种异常分类称为检查异常，因为编译器检查它们是否在代码中有处理了。<code>Throwable</code>类，<code>Exception</code>类和<code>Exception</code>类的子类(不包括<code>RuntimeException</code>类及其子类)称为检查异常。</p> 
 <p>所有未检查异常的异常称为未检查异常，因为编译器不检查它们是否在代码中有处理。<code>Error</code>类，<code>Error</code>类的所有子类，<code>RuntimeException</code>类及其所有子类都是未检查的异常。</p> 
 <p>当然也可以处理未检查的异常，但是这不是编译器强迫要求的。用于处理已检查或未检查异常的程序结构是相同的。</p> 
 <p>以下代码显示如何处理已检查的异常</p>   
 <pre><code class="lang-java">import java.io.IOException;

public class Main {
  public static void main(String[] argv) {
    try {
      int input = System.in.read();
      if (input != -1) {
        System.out.println(input);
      }
    } catch (IOException e) {
      System.out.print("IOException occurred.");
    }
  }
}
</code></pre>
 <br>      
</div></body></html>